### ISSUE TITLE
Feature: Export `randomCloid()`

### ISSUE THREAD

**Issue by defidefi5** [nktkas/hyperliquid#4]
It's not currently possible (that I know of) to import and use the `randomCloid()` function. I copied the implementation into my code locally, but it'd be nice if this could be imported from your library.

**Comment by nktkas** [comment]
I prefer this SDK to be low-level and only implement what is specified in the hyperliquid documentation.

As a compromise, it is possible to add a separate import point (example: import * as utils from "@nktkas/hyperliquid/utils"), but doing it only for randomCloid doesn't seem like a good idea to me. I'll come back to this idea when there are more reasons to implement it.

**Update**: The only brazen thing I allowed myself to do was to create a ReconnectingWebSocket. But I think it fits into the WebSocketTransport views.

**Comment by defidefi5** [comment]
Devil's advocate: the client OID is a particular format required by Hyperliquid (i.e. it's not merely a UUIDv4 or other common format), which is why it's useful to users of the hyperliquid client library. Most users of this lib will end up reinventing that wheel otherwise as most will need it.

**Comment by nktkas** [comment]
> Devil's advocate: the client OID is a particular format required by Hyperliquid (i.e. it's not merely a UUIDv4 or other common format), which is why it's useful to users of the hyperliquid client library. Most users of this lib will end up reinventing that wheel otherwise as most will need it.

You have made me study this issue in more detail)

What is cloid? - A unique order identifier for a particular user with no guarantee of idempotency.
What is the difference between cloid and oid? - oid is assigned by the server, while cloid is assigned by the user.
What scenarios use random cloid instead of oid? - The only thing I could think of is sending requests asynchronously without waiting for a response from the server.
My opinion: I think this is an extremely rare use case and creating a separate import point just for this doesn't seem like a good idea.

Can you give more scenarios where randomCloid is specifically needed or more ideas what can be added to the utils import point?

**Comment by nktkas** [comment]
Created a discussion https://github.com/nktkas/hyperliquid/discussions/9 on this topic.
