### ISSUE TITLE
Feature: `vaultAddress` parameter for `WalletClient`

### ISSUE THREAD

**Issue by defidefi5** [nktkas/hyperliquid#8]
**Description of the Desired Feature**

Hyperliquid requires specifying the `vaultAddress` to indicate which Hyperliquid subaccount to trade on.

Currently, it's necessary to provide vault address each time a method like `client.order()` is invoked, which is tedious and error prone.

If it were possible to provide the vaultAddress when defining WalletClient, this would be DRYer and less error prone.

**Additional info**

`vaultAddress` would have a type of `0x${string}`.

**Comment by nktkas** [comment]
I'm still not entirely sure, especially given the low-level nature of the library, but this change could really make life easier for many developers, albeit at the cost of complicating the constructor.

I agree to modify the WalletClient constructor so that it accepts a config object and add an optional defaultVaultAddress, which is used if the vault address is not explicitly specified in the method call.

**Comment by nktkas** [comment]
Implemented in https://github.com/nktkas/hyperliquid/commit/4ad416d3c207e7dc98e2a288621a51ccb7fc81ae in all methods except vaultTransfer.

Example of use:
```ts
import * as hl from "@nktkas/hyperliquid";
import { privateKeyToAccount } from "npm:viem/accounts";

const wallet = privateKeyToAccount("0x...");
const transport = new hl.HttpTransport();
const client = new hl.WalletClient({ wallet, transport, defaultVaultAddress: "0x..." });

// Supports the vaultAddress argument. Since it is not specified, defaultVaultAddress will be used.
await client.scheduleCancel({ time: Date.now() + 10000 });
// Same as:
// await client.scheduleCancel({ time: Date.now() + 10000, vaultAddress: "0x..." });
```

Explanation of why it is not implemented in vaultTransfer: The problem is that vaultTransfer requires vaultAddress to be present, unlike other methods, so it can end up with a situation where no vaultAddress is passed in the defaultVaultAddress or in the method arguments. TypeScript notices this. The only solution to this problem is to do a runtime check, but I think this is a bad solution because the SDK is TypeScript oriented and adding runtime checks can confuse developers into expecting vaultAddress to be optional (other methods don't have this problem because vaultAddress is not required for them to work).

**Comment by defidefi5** [comment]
Thanks!

**Comment by defidefi5** [comment]
Hi @nktkas if this is ready to go, could you publish please? still seeing 0.11.1 on JSR

<img width="172" alt="Screenshot 2025-01-05 at 12 32 30 PM" src="https://github.com/user-attachments/assets/a7af0e74-24d9-4737-a30f-748c39e4ac10" />
